language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

before_script:
  - cp .env.travis .env
  - travis_retry composer self-update
  - composer install --no-interaction --no-scripts --prefer-source --no-suggest

script:
- phpunit
